model_list:
  - model_name: "o3"
    litellm_params:
      model: openai/o3
      api_base: https://api.openai.com/v1
      api_key: os.environ/OPENAI_API_KEY
  - model_name: "gpt-5.1-codex-mini"
    litellm_params:
      model: custom_openai/gpt-5.1-codex-mini
      api_base: https://api.openai.com/v1
      api_key: os.environ/OPENAI_API_KEY
      additional_drop_params: ["parallel_tool_calls"]

#  - model_name: gpt-custom
#    litellm_params:
#      model: custom_openai/o4-mini
#      api_base: https://api.openai.com/v1
#      api_key: os.environ/OPENAI_API_KEY
#      additional_drop_params: ["parallel_tool_calls"]
  - model_name: gpt-custom
    litellm_params:
      model: custom_openai/o4-mini
      api_base: http://localhost:4000
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: o4-mini
    litellm_params:
      model: openai/o4-mini
      api_base: https://api.openai.com/v1
      api_key: os.environ/OPENAI_API_KEY
    model_info:
      base_model: openai/o4-mini

general_settings:
  store_prompts_in_spend_logs: true
  disable_endpoints: ["/v1/responses"]

litellm_settings:
  drop_params: true
  set_verbose: true
